name: union_shop
description: "A Flutter project for the University of Portsmouth union shop."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^6.0.0
  coverage: ^1.0.0
  shared_preferences: ^2.2.0
  firebase_core: ^3.6.0  # Core Firebase package
  firebase_auth: ^5.3.1  # Authentication package
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences_platform_interface: ^2.0.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Indentation matters! 2 spaces for 'assets', 4 spaces for the dash.
  assets:
    - assets/images/
    - assets/data/  # <--- Add this line